let PizzaList = [
  {
    id: 1,
    name: "Mussarela",
    img: "images/pizza.png",
    prices: [10.0, 15.0, 20.19],
    sizes: ["100g", "530g", "860g"],
    description:"Pizza tradicional Mussarela, uma ótima pedida. 🤤",
  },
  {
    id: 2,
    name: "Calabresa",
    img: "images/pizza2.png",
    prices: [10.0, 15.0, 18.0],
    sizes: ["320g", "530g", "860g"],
    description: "Pizza calabresa tradicional topissima. 😋",
  },
  {
    id: 3,
    name: "Quatro Queijos",
    img: "images/pizza3.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
  {
    id: 4,
    name: "Americana",
    img: "images/pizza4.png",
    prices: [10.0, 15.0, 19.77],
    sizes: ["320g", "530g", "860g"],
    description:"Pizza americana tradicional.",
  },
  {
    id: 5,
    name: "Portuguesa",
    img: "images/pizza5.png",
    prices: [10.0, 15.0, 21.43],
    sizes: ["320g", "530g", "860g"],
    description:"Pizza portuguesa, uma dellícia. 🤩",
  },
  {
    id: 6,
    name: "Moda da Casa",
    img: "images/pizza6.png",
    prices: [10.0, 15.0, 18.0],
    sizes: ["320g", "530g", "860g"],
    description:"Pizza especial á moda da casa, recomendo!",
  },
  {
    id: 7,
    name: "M&Ms",
    img: "images/pizza7.png",
    prices: [10.0, 15.0, 22.36],
    sizes: ["320g", "530g", "860g"],
    description:"Pizza doce de M&Ms e nutella, perfeito para fechar com chave de ouro.",
  },
];
